# Generated by Django 4.2.17 on 2025-07-04 05:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockLTH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20, unique=True)),
                ('lth_price', models.DecimalField(decimal_places=4, max_digits=15)),
                ('lth_date', models.DateField()),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('universe', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Stock Life Time High',
                'verbose_name_plural': 'Stock Life Time Highs',
                'db_table': 'core_stock_lth',
                'indexes': [models.Index(fields=['symbol'], name='core_stock__symbol_b92b3f_idx'), models.Index(fields=['universe'], name='core_stock__univers_bef814_idx')],
            },
        ),
    ]
