# Generated by Django 5.0.4 on 2024-05-02 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Signal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=20)),
                ("date", models.DateField()),
                ("buy_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("sell_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("expected_gain", models.DecimalField(decimal_places=2, max_digits=5)),
                ("strategy", models.CharField(max_length=100)),
                ("universe", models.CharField(max_length=100)),
            ],
        ),
    ]
